[package]
org = "ballerinax"
name = "github"
version = "0.99.10"
authors = ["Ballerina"]
keywords = ["github", "endpoint", "API"]
repository = "https://github.com/ballerina-platform/module-ballerinax-github"
license = ["Apache-2.0"]

[build-options]
observabilityIncluded = true
