[package]
org = "ballerinax"
name = "github"
version = "2.0.0"
export= ["github", "github.webhook"]
authors = ["Ballerina"]
keywords = ["IT Operations/Source Control", "Cost/Freemium"]
repository = "https://github.com/ballerina-platform/module-ballerinax-github"
license = ["Apache-2.0"]

[build-options]
observabilityIncluded = true

[[platform.java11.dependency]]
path = "../java-wrapper/build/libs/java-wrapper-0.99.15-SNAPSHOT.jar"
groupId = "io.ballerinax.webhook"
artifactId = "java-wrapper"
version = "0.99.15-SNAPSHOT"
