[package]
distribution = "2201.2.0"
org = "ballerinax"
name = "github"
version = "4.3.0"
authors = ["Ballerina"]
keywords = ["IT Operations/Source Control", "Cost/Freemium"]
icon = "icon.png"
repository = "https://github.com/ballerina-platform/module-ballerinax-github"
license = ["Apache-2.0"]

[build-options]
observabilityIncluded = true
