[package]
distribution = "2201.0.0"
org = "ballerinax"
name = "github"
version = "3.2.0"
export= ["github", "github.webhook"]
authors = ["Ballerina"]
keywords = ["IT Operations/Source Control", "Cost/Freemium"]
icon = "icon.png"
repository = "https://github.com/ballerina-platform/module-ballerinax-github"
license = ["Apache-2.0"]

[build-options]
observabilityIncluded = true

[[platform.java11.dependency]]
path = "../java-wrapper/build/libs/java-wrapper-3.2.0.jar"
groupId = "io.ballerinax.webhook"
artifactId = "java-wrapper"
version = "3.2.0"
