[[dependency]]
org = "ballerina"
name = "http"
version = "2.0.0"

[[dependency]]
org = "ballerina"
name = "regex"
version = "1.0.0"

[[dependency]]
org = "ballerina"
name = "log"
version = "2.0.0"

[[dependency]]
org = "ballerina"
name = "websub"
version = "2.0.0"

[[dependency]]
org = "ballerina"
name = "os"
version = "1.0.0"
