name: CI

on:
  push:
    branches-ignore:
      - "automated/dependency_version_update"
      - "automated/dependency_version_update_tmp"
  repository_dispatch:
    types:
      check_connector_for_breaking_changes

jobs:
    build:

        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - name: Ballerina Build
              uses: ballerina-platform/ballerina-action@nightly
              with:
                  args:
                      pack ./github
              env:
                  JAVA_HOME: /usr/lib/jvm/default-jvm
            - name: Ballerina Tests
              uses: ballerina-platform/ballerina-action@nightly
              with:
                  args:
                      test --test-report --code-coverage --coverage-format=xml ./github
              env:
                  ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
                  ORG_NAME: ${{ secrets.ORG_NAME }}
                  USER_REPO_NAME: ${{ secrets.REPO_NAME }}
                  ISSUE_ASSIGNEE: ${{ secrets.ASSIGNEE }}
                  RESOURCE_PATH: ${{ secrets.RESOURCE_PATH }}
                  JAVA_OPTS: -DBALLERINA_DEV_COMPILE_BALLERINA_ORG=true
                  GITHUB_USERNAME: ${{ secrets.USERNAME }}
                  
            - name: Upload coverage reports to Codecov
              uses: codecov/codecov-action@v3

            - name: Alert notifier on failure
              if: failure() && (github.event.action == 'check_connector_for_breaking_changes')
              run: |
                curl -X POST \
                'https://api.github.com/repos/ballerina-platform/ballerina-release/dispatches' \
                --header 'Accept: application/vnd.github.v3+json' \
                --header 'Authorization: Bearer ${{ secrets.BALLERINA_BOT_TOKEN }}' \
                --data-raw '{
                  "event_type": "notify-ballerinax-connector-build-failure",
                  "client_payload": {
                    "repoName": "module-ballerinax-github",
                    "workflow": "CI"
                  }
                }'
