name: Dev/Staging BCentral Release

on:
  workflow_dispatch:
    inputs:
      bal_central_environment:
        description: Ballerina Central Environment
        type: choice
        options:
        - STAGE
        - DEV
        required: true

jobs:
  release:
    runs-on: ubuntu-latest
    env: 
      BALLERINA_${{ github.event.inputs.bal_central_environment }}_CENTRAL: true
    steps:
      - uses: actions/checkout@v2
      - name: Ballerina Build
        uses: ballerina-platform/ballerina-action/@2201.1.1
        with:
          args:
            pack ./github
        env:
          JAVA_HOME: /usr/lib/jvm/default-jvm

      - name: Push to Staging
        if: github.event.inputs.bal_central_environment == 'STAGE'
        uses: ballerina-platform/ballerina-action/@2201.1.1
        with:
          args:
            push
        env:
          WORKING_DIR: ./github
          BALLERINA_CENTRAL_ACCESS_TOKEN: ${{ secrets.BALLERINA_CENTRAL_STAGE_ACCESS_TOKEN }}
      
      - name: Push to Dev
        if: github.event.inputs.bal_central_environment == 'DEV'
        uses: ballerina-platform/ballerina-action/@2201.1.1
        with:
          args:
            push
        env:
          WORKING_DIR: ./github
          JAVA_HOME: /usr/lib/jvm/default-jvm
          BALLERINA_CENTRAL_ACCESS_TOKEN: ${{ secrets.BALLERINA_CENTRAL_DEV_ACCESS_TOKEN }}
